$terminal = runapp footclient
$browser = runapp helium-browser --new-window --ozone-platform=wayland --disable-features=WaylandWpColorManagerV1
$webapp = runapp chromium --new-window --ozone-platform=wayland --disable-features=WaylandWpColorManagerV1 --app

bindd = SUPER, return, Open terminal, exec, $terminal
bindd = SUPER, F, Open file manager, exec, runapp thunar
bindd = SUPER, B, Open browser, exec, $browser
bindd = SUPER, M, Open music player, exec, ~/.config/hypr/scripts/launch-or-focus spotify-launcher
bindd = SUPER, G, Open WhatsApp, exec, $webapp="https://web.whatsapp.com/"
bindd = SUPER, D, Open Discord, exec, runapp discord

bind = , SCROLL_LOCK, exec, voxtype record toggle
bind = SHIFT, SCROLL_LOCK, exec, voxtype record toggle --profile translate_mode
bind = CTRL, SCROLL_LOCK, exec, voxtype record toggle --profile code_snippet
bind = SUPER, SCROLL_LOCK, exec, voxtype record cancel

bindd = SUPERCTRL, Q, Power off system, exec, systemctl poweroff