#!/bin/bash

if [[ $(hyprctl -j getoption general:layout | jq -r '.str') = "master" ]]; then
  hyprctl keyword general:layout "dwindle"
  notify-send "Layout" "Dwindle" -i /usr/share/icons/Papirus/32x32/apps/workspace-switcher.svg
else
  hyprctl keyword general:layout "master"
  notify-send "Layout" "Master" -i /usr/share/icons/Papirus/32x32/apps/workspace-switcher.svg
fi