# Floating windows
windowrule = float on, center on, size 800 600, match:tag floating-window

windowrule = tag +floating-window, match:class (blueberry.py|Impala|Wiremix|org.gnome.NautilusPreviewer|com.gabm.satty|About|TUI.float)
windowrule = tag +floating-window, match:class (xdg-desktop-portal-gtk|sublime_text|DesktopEditors|org.gnome.Nautilus|helium), match:title ^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files)
windowrule = tag +floating-window, match:class helium, match:title .*wants to save.*

# Match modal dialogs
windowrule = tag +floating-window, match:modal true

# Thunar dialogs
windowrule = float on, center on, size 400 100, match:tag thunar-dialog

windowrule = tag +thunar-dialog, match:class thunar, match:title ^(File Operation Progress|Rename|Confirm|Move to Trash|Replace|Error|Failed).*$

# Fullscreen screensaver
windowrule = fullscreen on, match:class Screensaver
