#!/bin/sh

selection="$(printf '%s\n' \
  'Power off' \
  'Reboot' \
  'Suspend' \
  'Log out' \
  'Lock' |
  tofi --prompt-text 'Power: ')"

case "$selection" in
  'Power off')
    exec systemctl poweroff
    ;;
  'Reboot')
    exec systemctl reboot
    ;;
  'Suspend')
    exec systemctl suspend
    ;;
  'Log out')
    exec hyprctl dispatch exit
    ;;
  'Lock')
    exec ~/.config/hypr/scripts/lock-screen
    ;;
esac
