[greeter]
background = /usr/share/images/wallpaper.png
theme-name = Catppuccin-Mocha-Standard-Mauve-Dark
icon-theme-name = Catppuccin-Mocha-Dark-Cursors
font-name = NotoSansM Nerd Font 11
user-background = false

